### ISSUE TITLE
List.extracting doesn't work by index for list of dicts

### ISSUE THREAD

**Issue by zaz600** [ActivisionGameScience/assertpy#86] opened 2018-11-08 08:18 UTC
pytest example

```
class TestExtracting:
    def test_list_of_lists(self):
        people = [['Fred', 'Smith'], ['Bob', 'Barr']]
        assert_that(people).extracting(0).is_equal_to(['Fred','Bob'])
        assert_that(people).extracting(-1).is_equal_to(['Smith','Barr'])

    def test_list_of_dicts(self):
        people = [{'name': 'Smith'}, {'name': 'Barr'}]
        assert_that(people).extracting(0).contains_only("name")
        assert_that(people).extracting(-1).contains_only("name")

    def test_list_of_dicts_2(self):
        people = [{'name': 'Smith'}, {'name': 'Barr'}]
        assert_that(people).extracting("name").is_equal_to(['Smith', 'Barr'])

```

test_list_of_lists passed.
test_list_of_dicts_2 passed
test_list_of_dicts failed with message

```
    def test_list_of_dicts(self):
        people = [{'name': 'Smith'}, {'name': 'Barr'}]
>       assert_that(people).extracting(0).contains_only("name")
E       ValueError: item keys ['name'] did not contain key <0>
```

For some reason i need to extract element from list of dicts by index not only values by key
Maybe i can do this?
```
assert_that(people).extracting(index=0).contains_only("name")
assert_that(people).extracting("name").is_equal_to(['Smith', 'Barr'])
```

**Comment by saturnboy** [comment] 2018-11-15 18:42
@zaz600 the `extracting` helper is designed to flatten a collection (on a key, on an index, etc), so:

1. for a list of lists, you flatten on index -> make a new list of items, taking just the Nth item from each sublist
1. for a list of dicts, you flatten on key -> make a new list of items, taking just the <key>th item from each sub-dict

There is no such thing as indexing into a dict in python, by definition they are un-ordered.

**Comment by saturnboy** [comment] 2018-11-18 15:56
Won't fix - it's not a bug that you can not index into a dict...they are un-ordered by definition.

**Closed by saturnboy** 2018-11-18 15:56 UTC
Labels: wontfix

**Comment by zaz600** [comment] 2018-11-18 16:53
you didn't understand me
i don't want to index via dict. i want access to LIST element at index. never mind which type has this element: dict or list 

```
people = [{'name': 'Smith', 'age': 22}, {'name': 'Barr', 'age': 33}]
# check keys
assert_that(people).extracting(index=0).contains_only("name", "age")
# check values of dict
assert_that(people).extracting("name").is_equal_to(['Smith', 'Barr'])
```

i want to check which keys contains first (n-th) element of list of dicts. than i want to check it  values
```
assert_that(people).extracting(index=0).contains_only("name", "age").extracting("name").is_equal_to(['Smith', 'Barr'])
```

In current version i need do it like this:
```
assert_that(people[0]).contains_only("name", "age")
assert_that(people).extracting("name").is_equal_to(['Smith', 'Barr'])
```
 I want to check keys of dict in list of dict without explicit indexing with `[0]`

```
assert_that(people).extracting(index=0).contains_only("name", "age").extracting("name").is_equal_to(['Smith', 'Barr'])
```
